/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/ui/button/Button.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElTable: typeof import('element-plus/es')['ElTable']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./../src/components/ui/separator/Separator.vue')['default']
    Sheet: typeof import('./../src/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./../src/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./../src/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./../src/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./../src/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./../src/components/ui/sheet/SheetHeader.vue')['default']
    SheetOverlay: typeof import('./../src/components/ui/sheet/SheetOverlay.vue')['default']
    SheetTitle: typeof import('./../src/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./../src/components/ui/sheet/SheetTrigger.vue')['default']
    Toggle: typeof import('./../src/components/ui/toggle/Toggle.vue')['default']
    ToggleGroup: typeof import('./../src/components/ui/toggle-group/ToggleGroup.vue')['default']
    ToggleGroupItem: typeof import('./../src/components/ui/toggle-group/ToggleGroupItem.vue')['default']
    XFooter: typeof import('./../src/components/XFooter.vue')['default']
    XHeader: typeof import('./../src/components/header/XHeader.vue')['default']
    XPerformance: typeof import('./../src/components/header/XPerformance.vue')['default']
    XSettings: typeof import('./../src/components/header/XSettings.vue')['default']
  }
}
