/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/ui/button/Button.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./../src/components/ui/separator/Separator.vue')['default']
    Sheet: typeof import('./../src/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./../src/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./../src/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./../src/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./../src/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./../src/components/ui/sheet/SheetHeader.vue')['default']
    SheetOverlay: typeof import('./../src/components/ui/sheet/SheetOverlay.vue')['default']
    SheetTitle: typeof import('./../src/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./../src/components/ui/sheet/SheetTrigger.vue')['default']
    Toggle: typeof import('./../src/components/ui/toggle/Toggle.vue')['default']
    XFooter: typeof import('./../src/components/XFooter.vue')['default']
    XHeader: typeof import('./../src/components/header/XHeader.vue')['default']
    XPerformance: typeof import('./../src/components/header/XPerformance.vue')['default']
    XSettings: typeof import('./../src/components/header/XSettings.vue')['default']
  }
}
