/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./../src/components/ui/button/Button.vue')['default']
    Command: typeof import('./../src/components/ui/command/Command.vue')['default']
    CommandDialog: typeof import('./../src/components/ui/command/CommandDialog.vue')['default']
    CommandEmpty: typeof import('./../src/components/ui/command/CommandEmpty.vue')['default']
    CommandGroup: typeof import('./../src/components/ui/command/CommandGroup.vue')['default']
    CommandInput: typeof import('./../src/components/ui/command/CommandInput.vue')['default']
    CommandItem: typeof import('./../src/components/ui/command/CommandItem.vue')['default']
    CommandList: typeof import('./../src/components/ui/command/CommandList.vue')['default']
    CommandSeparator: typeof import('./../src/components/ui/command/CommandSeparator.vue')['default']
    CommandShortcut: typeof import('./../src/components/ui/command/CommandShortcut.vue')['default']
    Dialog: typeof import('./../src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./../src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./../src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./../src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./../src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./../src/components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./../src/components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./../src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./../src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./../src/components/ui/dialog/DialogTrigger.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('./../src/components/ui/separator/Separator.vue')['default']
    Sheet: typeof import('./../src/components/ui/sheet/Sheet.vue')['default']
    SheetClose: typeof import('./../src/components/ui/sheet/SheetClose.vue')['default']
    SheetContent: typeof import('./../src/components/ui/sheet/SheetContent.vue')['default']
    SheetDescription: typeof import('./../src/components/ui/sheet/SheetDescription.vue')['default']
    SheetFooter: typeof import('./../src/components/ui/sheet/SheetFooter.vue')['default']
    SheetHeader: typeof import('./../src/components/ui/sheet/SheetHeader.vue')['default']
    SheetOverlay: typeof import('./../src/components/ui/sheet/SheetOverlay.vue')['default']
    SheetTitle: typeof import('./../src/components/ui/sheet/SheetTitle.vue')['default']
    SheetTrigger: typeof import('./../src/components/ui/sheet/SheetTrigger.vue')['default']
    Sonner: typeof import('./../src/components/ui/sonner/Sonner.vue')['default']
    Toggle: typeof import('./../src/components/ui/toggle/Toggle.vue')['default']
    XCommand: typeof import('./../src/components/XCommand.vue')['default']
    XFooter: typeof import('./../src/components/XFooter.vue')['default']
    XHeader: typeof import('./../src/components/header/XHeader.vue')['default']
    XPerformance: typeof import('./../src/components/header/XPerformance.vue')['default']
    XSettings: typeof import('./../src/components/header/XSettings.vue')['default']
  }
}
